import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div
          className='sticky top-0 bg-white shadow-md w-full'
          style={{ position: "fixed" }}
        >
          <div className='max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8'>
            <div className='flex items-center justify-between'>
              <a href='#' className='flex-shrink-0'>
                <img
                  className='h-8 w-auto'
                  src='https://via.placeholder.com/50x50'
                  alt='Logo'
                />
              </a>
              <div className='ml-10 flex items-center space-x-4'>
                <a href='/' className='text-gray-500 hover:text-gray-900'>
                  Home
                </a>
              </div>

              <div className='hidden md:flex items-center justify-end md:flex-1 lg:w-0'>
                <a
                  href='#'
                  className='ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-green-300 hover:bg-green-600'
                >
                  Cart (2)
                </a>
              </div>
            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  )
}
